global:
  scrape_interval: 15s
  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'  # Для DB
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'node_exporter'  # Для Node
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'custom_exporter'  # Для Custom
    static_configs:
      - targets: ['custom_exporter:8000']